title: Gud Branch
description: Get gud at git branching. A website about good git branching practices and other git tips.
url_DISABLED: https://____

remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: localTheme

# Set a path/url to a logo that will be displayed instead of the title
logo_DISABLED: "/assets/images/logo.png"

# JTD links.
aux_links_new_tab: true
aux_links:
  repo: {{ https://github.com/reidgould/gud_branch }}
  Official Git Book: https://git-scm.com/book/en/v2

# JTD navigation.
nav_sort: case_insensitive

# GitHub link in Footer of JTD.
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View on GitHub"
gh_edit_repository: "https://github.com/reidgould/gud_branch" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# JTD callouts.
callouts:
  note:
    color: blue
  note-titled:
    title: Note
    color: blue
